### ISSUE TITLE
AudioWaveform::Error: Cannot load data file version: 70468681

### ISSUE THREAD

**Issue by Joshfindit** [bbc/audio_waveform-ruby#2]
Can not get audio_waveform-ruby to work.
`audiowaveform -i /home/josh/file.mp3 --pixels-per-second 1 -b 8 -o file.json` does work

```
waveform = AudioWaveform::WaveformDataFile.new(filename: "/home/josh/file.mp3")
AudioWaveform::Error: Cannot load data file version: 70468681
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/audio_waveform-ruby-1.0.1/lib/audio_waveform/waveform_data_file.rb:254:in `read_header'
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/audio_waveform-ruby-1.0.1/lib/audio_waveform/waveform_data_file.rb:228:in `block in read'
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/audio_waveform-ruby-1.0.1/lib/audio_waveform/waveform_data_file.rb:227:in `open'
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/audio_waveform-ruby-1.0.1/lib/audio_waveform/waveform_data_file.rb:227:in `read'
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/audio_waveform-ruby-1.0.1/lib/audio_waveform/waveform_data_file.rb:23:in `initialize'
    from (irb):3:in `new'
    from (irb):3
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.rc1/lib/rails/commands/console.rb:65:in `start'
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.rc1/lib/rails/commands/console_helper.rb:9:in `start'
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /home/josh/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
    from bin/rails:9:in `require'
    from bin/rails:9:in `<main>'
```

```
Linux 3.19.0-25-generic #26~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
Using rails 5.0.0.rc1
Using audio_waveform-ruby 1.0.1 # Also tried  audio_waveform-ruby 1.0.2 (was 1.0.1) from https://github.com/bbcrd/audio_waveform-ruby.git (at master@2778d73). Same error
```

**Comment by chrisn** [comment]
audio_waveform-ruby can only load binary format waveform data files, and you're passing the name of an MP3 file. Try this:

```
audiowaveform -i file.mp3 --pixels-per-second 1 -b 8 -o file.dat
```

Then

```
waveform = AudioWaveform::WaveformDataFile.new(filename: "file.dat")
```

**Comment by Joshfindit** [comment]
Ahhhh, that makes sense, and thank you.
is there a way to get the data from an audio file using audio_waveform-ruby?

**Comment by chrisn** [comment]
There isn't, no, although you could modify audio_waveform-ruby to invoke [audiowaveform](https://github.com/bbcrd/audiowaveform). We intentionally wrote the software to create waveform data as a stand-alone program, to comply with the license (GPL) of the third party we've code used.
